export interface SeoPage {
  slug: string;
  title: string;
  description: string;
  heading: string;
  type: "contractor-state" | "situation";
  state?: string;
  contractorType?: string;
}

export const SEO_PAGES: SeoPage[] = [
  // Contractor-state pages
  {
    slug: "subcontractor-lien-rights-california",
    title: "Subcontractor Lien Rights in California | LienFile.io",
    description: "Learn how to protect your lien rights as a subcontractor in California. File preliminary notices and mechanic's liens online with LienFile.io.",
    heading: "Subcontractor Lien Rights in California",
    type: "contractor-state",
    state: "california",
    contractorType: "Subcontractor",
  },
  {
    slug: "general-contractor-lien-rights-texas",
    title: "General Contractor Lien Rights in Texas | LienFile.io",
    description: "Texas mechanic's lien guide for general contractors. Understand deadlines, filing requirements, and protect your right to payment.",
    heading: "General Contractor Lien Rights in Texas",
    type: "contractor-state",
    state: "texas",
    contractorType: "General Contractor",
  },
  {
    slug: "material-supplier-lien-rights-florida",
    title: "Material Supplier Lien Rights in Florida | LienFile.io",
    description: "Florida lien rights guide for material suppliers. Learn Notice to Owner requirements, deadlines, and how to file a mechanic's lien.",
    heading: "Material Supplier Lien Rights in Florida",
    type: "contractor-state",
    state: "florida",
    contractorType: "Material Supplier",
  },
  {
    slug: "subcontractor-lien-rights-new-york",
    title: "Subcontractor Lien Rights in New York | LienFile.io",
    description: "New York mechanic's lien guide for subcontractors. No preliminary notice required. File your lien within 8 months of last work.",
    heading: "Subcontractor Lien Rights in New York",
    type: "contractor-state",
    state: "new-york",
    contractorType: "Subcontractor",
  },
  {
    slug: "general-contractor-lien-rights-illinois",
    title: "General Contractor Lien Rights in Illinois | LienFile.io",
    description: "Illinois mechanic's lien guide for general contractors. Understand 4-month filing deadlines, notice requirements, and enforcement.",
    heading: "General Contractor Lien Rights in Illinois",
    type: "contractor-state",
    state: "illinois",
    contractorType: "General Contractor",
  },
  {
    slug: "subcontractor-lien-rights-pennsylvania",
    title: "Subcontractor Lien Rights in Pennsylvania | LienFile.io",
    description: "Pennsylvania lien rights guide for subcontractors. Learn about preliminary notice requirements and 6-month filing deadline.",
    heading: "Subcontractor Lien Rights in Pennsylvania",
    type: "contractor-state",
    state: "pennsylvania",
    contractorType: "Subcontractor",
  },
  {
    slug: "material-supplier-lien-rights-ohio",
    title: "Material Supplier Lien Rights in Ohio | LienFile.io",
    description: "Ohio lien rights for material suppliers. Understand the 21-day Notice of Furnishing requirement and 75-day filing deadline.",
    heading: "Material Supplier Lien Rights in Ohio",
    type: "contractor-state",
    state: "ohio",
    contractorType: "Material Supplier",
  },
  {
    slug: "general-contractor-lien-rights-georgia",
    title: "General Contractor Lien Rights in Georgia | LienFile.io",
    description: "Georgia mechanic's lien guide for general contractors. 90-day filing deadline from completion. File online with LienFile.io.",
    heading: "General Contractor Lien Rights in Georgia",
    type: "contractor-state",
    state: "georgia",
    contractorType: "General Contractor",
  },
  {
    slug: "subcontractor-lien-rights-michigan",
    title: "Subcontractor Lien Rights in Michigan | LienFile.io",
    description: "Michigan lien rights for subcontractors. Learn about the 20-day Notice of Furnishing and 90-day filing deadline.",
    heading: "Subcontractor Lien Rights in Michigan",
    type: "contractor-state",
    state: "michigan",
    contractorType: "Subcontractor",
  },
  {
    slug: "general-contractor-lien-rights-arizona",
    title: "General Contractor Lien Rights in Arizona | LienFile.io",
    description: "Arizona mechanic's lien guide for general contractors. 20-day preliminary notice and 120-day filing deadline.",
    heading: "General Contractor Lien Rights in Arizona",
    type: "contractor-state",
    state: "arizona",
    contractorType: "General Contractor",
  },
  {
    slug: "subcontractor-lien-rights-washington",
    title: "Subcontractor Lien Rights in Washington | LienFile.io",
    description: "Washington state lien rights for subcontractors. 60-day notice to owner requirement and 90-day filing deadline.",
    heading: "Subcontractor Lien Rights in Washington",
    type: "contractor-state",
    state: "washington",
    contractorType: "Subcontractor",
  },
  {
    slug: "material-supplier-lien-rights-colorado",
    title: "Material Supplier Lien Rights in Colorado | LienFile.io",
    description: "Colorado lien rights guide for material suppliers. Notice of Intent required 10 business days before filing.",
    heading: "Material Supplier Lien Rights in Colorado",
    type: "contractor-state",
    state: "colorado",
    contractorType: "Material Supplier",
  },
  {
    slug: "general-contractor-lien-rights-virginia",
    title: "General Contractor Lien Rights in Virginia | LienFile.io",
    description: "Virginia mechanic's lien guide for general contractors. 90-day filing deadline from last day of the month of last work.",
    heading: "General Contractor Lien Rights in Virginia",
    type: "contractor-state",
    state: "virginia",
    contractorType: "General Contractor",
  },
  {
    slug: "subcontractor-lien-rights-north-carolina",
    title: "Subcontractor Lien Rights in North Carolina | LienFile.io",
    description: "North Carolina lien rights for subcontractors. Notice to Lien Agent required within 15 days. 120-day filing deadline.",
    heading: "Subcontractor Lien Rights in North Carolina",
    type: "contractor-state",
    state: "north-carolina",
    contractorType: "Subcontractor",
  },
  {
    slug: "general-contractor-lien-rights-massachusetts",
    title: "General Contractor Lien Rights in Massachusetts | LienFile.io",
    description: "Massachusetts mechanic's lien guide for general contractors. 120-day filing deadline and enforcement requirements.",
    heading: "General Contractor Lien Rights in Massachusetts",
    type: "contractor-state",
    state: "massachusetts",
    contractorType: "General Contractor",
  },
  {
    slug: "subcontractor-lien-rights-new-jersey",
    title: "Subcontractor Lien Rights in New Jersey | LienFile.io",
    description: "New Jersey lien rights guide for subcontractors. Notice of Unpaid Balance requirements and 90-day filing deadline.",
    heading: "Subcontractor Lien Rights in New Jersey",
    type: "contractor-state",
    state: "new-jersey",
    contractorType: "Subcontractor",
  },
  {
    slug: "material-supplier-lien-rights-minnesota",
    title: "Material Supplier Lien Rights in Minnesota | LienFile.io",
    description: "Minnesota lien rights for material suppliers. 45-day pre-lien notice and 120-day filing deadline.",
    heading: "Material Supplier Lien Rights in Minnesota",
    type: "contractor-state",
    state: "minnesota",
    contractorType: "Material Supplier",
  },
  {
    slug: "general-contractor-lien-rights-tennessee",
    title: "General Contractor Lien Rights in Tennessee | LienFile.io",
    description: "Tennessee mechanic's lien guide for general contractors. 90-day filing deadline. Notice of Nonpayment requirements.",
    heading: "General Contractor Lien Rights in Tennessee",
    type: "contractor-state",
    state: "tennessee",
    contractorType: "General Contractor",
  },
  {
    slug: "subcontractor-lien-rights-maryland",
    title: "Subcontractor Lien Rights in Maryland | LienFile.io",
    description: "Maryland lien rights for subcontractors. 120-day notice requirement and 180-day filing deadline.",
    heading: "Subcontractor Lien Rights in Maryland",
    type: "contractor-state",
    state: "maryland",
    contractorType: "Subcontractor",
  },
  {
    slug: "general-contractor-lien-rights-oregon",
    title: "General Contractor Lien Rights in Oregon | LienFile.io",
    description: "Oregon mechanic's lien guide for general contractors. Notice of Right to Lien and 75-day filing deadline.",
    heading: "General Contractor Lien Rights in Oregon",
    type: "contractor-state",
    state: "oregon",
    contractorType: "General Contractor",
  },
  {
    slug: "subcontractor-lien-rights-indiana",
    title: "Subcontractor Lien Rights in Indiana | LienFile.io",
    description: "Indiana lien rights for subcontractors. 90-day filing deadline and notice requirements.",
    heading: "Subcontractor Lien Rights in Indiana",
    type: "contractor-state",
    state: "indiana",
    contractorType: "Subcontractor",
  },
  {
    slug: "general-contractor-lien-rights-missouri",
    title: "General Contractor Lien Rights in Missouri | LienFile.io",
    description: "Missouri mechanic's lien guide for general contractors. 6-month filing deadline and enforcement procedures.",
    heading: "General Contractor Lien Rights in Missouri",
    type: "contractor-state",
    state: "missouri",
    contractorType: "General Contractor",
  },
  {
    slug: "material-supplier-lien-rights-wisconsin",
    title: "Material Supplier Lien Rights in Wisconsin | LienFile.io",
    description: "Wisconsin lien rights for material suppliers. Notice of Intent requirements and 6-month filing deadline.",
    heading: "Material Supplier Lien Rights in Wisconsin",
    type: "contractor-state",
    state: "wisconsin",
    contractorType: "Material Supplier",
  },
  {
    slug: "subcontractor-lien-rights-nevada",
    title: "Subcontractor Lien Rights in Nevada | LienFile.io",
    description: "Nevada lien rights for subcontractors. 31-day Notice of Right to Lien and 90-day filing deadline.",
    heading: "Subcontractor Lien Rights in Nevada",
    type: "contractor-state",
    state: "nevada",
    contractorType: "Subcontractor",
  },
  {
    slug: "general-contractor-lien-rights-utah",
    title: "General Contractor Lien Rights in Utah | LienFile.io",
    description: "Utah mechanic's lien guide for general contractors. State Construction Registry and 180-day filing deadline.",
    heading: "General Contractor Lien Rights in Utah",
    type: "contractor-state",
    state: "utah",
    contractorType: "General Contractor",
  },
  // Situation-based pages
  {
    slug: "how-to-file-a-mechanics-lien",
    title: "How to File a Mechanic's Lien: Step-by-Step Guide | LienFile.io",
    description: "Complete guide to filing a mechanic's lien. Learn deadlines, requirements, and the step-by-step process to protect your right to payment.",
    heading: "How to File a Mechanic's Lien: Step-by-Step Guide",
    type: "situation",
  },
  {
    slug: "preliminary-notice-guide",
    title: "Preliminary Notice Guide: When and How to Send | LienFile.io",
    description: "Everything you need to know about preliminary notices. Which states require them, deadlines, who to send them to, and templates.",
    heading: "The Complete Preliminary Notice Guide",
    type: "situation",
  },
  {
    slug: "what-to-do-when-a-contractor-doesnt-pay",
    title: "What to Do When a Contractor Doesn't Pay | LienFile.io",
    description: "Step-by-step guide for subcontractors and suppliers who haven't been paid. Learn your options from demand letters to mechanic's liens.",
    heading: "What to Do When a Contractor Doesn't Pay You",
    type: "situation",
  },
  {
    slug: "mechanics-lien-vs-bond-claim",
    title: "Mechanic's Lien vs Bond Claim: Which One Do You Need? | LienFile.io",
    description: "Understand the difference between mechanic's liens and bond claims. Learn which remedy applies to your construction project.",
    heading: "Mechanic's Lien vs Bond Claim: Which One Do You Need?",
    type: "situation",
  },
  {
    slug: "can-a-subcontractor-file-a-lien",
    title: "Can a Subcontractor File a Lien? Rights and Requirements | LienFile.io",
    description: "Yes, subcontractors can file mechanic's liens in all 50 states. Learn the specific requirements, deadlines, and notice obligations.",
    heading: "Can a Subcontractor File a Mechanic's Lien?",
    type: "situation",
  },
  {
    slug: "mechanics-lien-on-residential-property",
    title: "Mechanic's Lien on Residential Property: What Homeowners and Contractors Need to Know | LienFile.io",
    description: "Guide to mechanic's liens on residential properties. Special rules, homeowner protections, and contractor filing requirements.",
    heading: "Mechanic's Liens on Residential Property",
    type: "situation",
  },
  {
    slug: "how-to-release-a-mechanics-lien",
    title: "How to Release a Mechanic's Lien | LienFile.io",
    description: "Step-by-step guide to releasing a mechanic's lien after payment. Templates, filing requirements, and deadlines by state.",
    heading: "How to Release a Mechanic's Lien",
    type: "situation",
  },
  {
    slug: "notice-of-intent-to-lien",
    title: "Notice of Intent to Lien: Template and Guide | LienFile.io",
    description: "How to write and send a notice of intent to file a mechanic's lien. Free template, requirements by state, and when to send it.",
    heading: "Notice of Intent to Lien: Template and Guide",
    type: "situation",
  },
  {
    slug: "construction-payment-disputes",
    title: "Construction Payment Disputes: Your Options Explained | LienFile.io",
    description: "Complete guide to handling construction payment disputes. From negotiation to mechanic's liens, understand all your legal options.",
    heading: "Construction Payment Disputes: Your Options Explained",
    type: "situation",
  },
  {
    slug: "lien-rights-for-material-suppliers",
    title: "Lien Rights for Material Suppliers: A Complete Guide | LienFile.io",
    description: "Material supplier lien rights in all 50 states. Notice requirements, deadlines, and step-by-step filing instructions.",
    heading: "Lien Rights for Material Suppliers",
    type: "situation",
  },
  {
    slug: "mechanics-lien-deadline-calculator",
    title: "Mechanic's Lien Deadline Calculator | LienFile.io",
    description: "Calculate your mechanic's lien filing deadline based on your state, role, and last day of work. Never miss a critical deadline.",
    heading: "Mechanic's Lien Deadline Calculator",
    type: "situation",
  },
  {
    slug: "construction-lien-waiver-guide",
    title: "Construction Lien Waiver Guide: Types and When to Sign | LienFile.io",
    description: "Understand conditional vs unconditional lien waivers. Learn when to sign, what to look for, and how to protect your rights.",
    heading: "Construction Lien Waiver Guide",
    type: "situation",
  },
  {
    slug: "filing-a-lien-as-an-equipment-rental-company",
    title: "Filing a Lien as an Equipment Rental Company | LienFile.io",
    description: "Equipment rental companies can file mechanic's liens. Learn state-specific requirements, notice deadlines, and filing procedures.",
    heading: "Filing a Mechanic's Lien as an Equipment Rental Company",
    type: "situation",
  },
  {
    slug: "how-long-does-a-mechanics-lien-last",
    title: "How Long Does a Mechanic's Lien Last? State-by-State Guide | LienFile.io",
    description: "Mechanic's lien duration varies by state from 30 days to 6 years. Learn enforcement deadlines and how to extend your lien.",
    heading: "How Long Does a Mechanic's Lien Last?",
    type: "situation",
  },
  {
    slug: "public-works-lien-rights",
    title: "Public Works Lien Rights and Bond Claims | LienFile.io",
    description: "You cannot file a lien on public property. Learn about bond claims under the Miller Act and state Little Miller Acts.",
    heading: "Public Works Projects: Bond Claims Instead of Liens",
    type: "situation",
  },
  {
    slug: "protecting-lien-rights-on-commercial-projects",
    title: "Protecting Your Lien Rights on Commercial Projects | LienFile.io",
    description: "Commercial construction lien rights guide. Preliminary notices, filing deadlines, and strategies to protect your payment rights.",
    heading: "Protecting Your Lien Rights on Commercial Projects",
    type: "situation",
  },
  {
    slug: "cost-of-filing-a-mechanics-lien",
    title: "How Much Does It Cost to File a Mechanic's Lien? | LienFile.io",
    description: "Breakdown of mechanic's lien filing costs: recording fees, attorney fees, service costs, and how LienFile.io saves you money.",
    heading: "How Much Does It Cost to File a Mechanic's Lien?",
    type: "situation",
  },
  {
    slug: "mechanics-lien-for-unpaid-labor",
    title: "Mechanic's Lien for Unpaid Labor: Protecting Workers' Rights | LienFile.io",
    description: "Laborers and workers have lien rights too. Learn how to file a mechanic's lien for unpaid wages on construction projects.",
    heading: "Mechanic's Lien for Unpaid Labor",
    type: "situation",
  },
  {
    slug: "what-happens-after-filing-a-mechanics-lien",
    title: "What Happens After You File a Mechanic's Lien? | LienFile.io",
    description: "Timeline of events after filing a mechanic's lien. From owner notification to enforcement, payment, or release.",
    heading: "What Happens After You File a Mechanic's Lien?",
    type: "situation",
  },
  {
    slug: "mechanics-lien-mistakes-to-avoid",
    title: "10 Common Mechanic's Lien Mistakes to Avoid | LienFile.io",
    description: "Avoid these common mechanic's lien filing mistakes that can invalidate your claim. Deadlines, notice errors, and more.",
    heading: "10 Common Mechanic's Lien Mistakes to Avoid",
    type: "situation",
  },
  {
    slug: "demand-letter-before-filing-a-lien",
    title: "How to Write a Demand Letter Before Filing a Mechanic's Lien | LienFile.io",
    description: "Template and guide for writing an effective demand letter before filing a mechanic's lien. Often resolves disputes without litigation.",
    heading: "Writing a Demand Letter Before Filing a Lien",
    type: "situation",
  },
  {
    slug: "general-contractor-lien-rights-louisiana",
    title: "General Contractor Lien Rights in Louisiana | LienFile.io",
    description: "Louisiana mechanic's lien guide for general contractors. Notice of Contract, filing procedures, and privilege deadlines.",
    heading: "General Contractor Lien Rights in Louisiana",
    type: "contractor-state",
    state: "louisiana",
    contractorType: "General Contractor",
  },
  {
    slug: "general-contractor-lien-rights-colorado",
    title: "General Contractor Lien Rights in Colorado | LienFile.io",
    description: "Colorado mechanic's lien guide for general contractors. Notice of Intent requirements and 4-month filing deadline.",
    heading: "General Contractor Lien Rights in Colorado",
    type: "contractor-state",
    state: "colorado",
    contractorType: "General Contractor",
  },
  {
    slug: "material-supplier-lien-rights-washington",
    title: "Material Supplier Lien Rights in Washington | LienFile.io",
    description: "Washington lien rights guide for material suppliers. 60-day notice requirement and 90-day filing deadline.",
    heading: "Material Supplier Lien Rights in Washington",
    type: "contractor-state",
    state: "washington",
    contractorType: "Material Supplier",
  },
  {
    slug: "subcontractor-lien-rights-connecticut",
    title: "Subcontractor Lien Rights in Connecticut | LienFile.io",
    description: "Connecticut mechanic's lien guide for subcontractors. 90-day filing deadline from last furnishing labor or materials.",
    heading: "Subcontractor Lien Rights in Connecticut",
    type: "contractor-state",
    state: "connecticut",
    contractorType: "Subcontractor",
  },
];
