export interface StateData {
  name: string;
  slug: string;
  abbreviation: string;
  preliminaryNotice: {
    required: boolean;
    deadline: string;
    whoToSendTo: string;
  };
  lienDeadline: string;
  whoCanFile: string[];
  whereToFile: string;
  serviceRequirements: string;
  enforcementDeadline: string;
  lienAmountLimits: string;
  statute: string;
}

export const STATES: Record<string, StateData> = {
  alabama: {
    name: "Alabama",
    slug: "alabama",
    abbreviation: "AL",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "6 months from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Probate Court in the county where the property is located",
    serviceRequirements: "Serve copy on property owner within 10 days of filing",
    enforcementDeadline: "6 months from filing the lien",
    lienAmountLimits: "Limited to the value of labor or materials furnished",
    statute: "Ala. Code § 35-11-210 et seq.",
  },
  alaska: {
    name: "Alaska",
    slug: "alaska",
    abbreviation: "AK",
    preliminaryNotice: {
      required: true,
      deadline: "15 days before filing lien (Notice of Right to Lien must be posted at job site)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "120 days from completion of the project",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "District Recorder's Office in the recording district where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 15 days of recording",
    enforcementDeadline: "6 months from completion of the project",
    lienAmountLimits: "Limited to the amount agreed upon or reasonable value of labor/materials",
    statute: "Alaska Stat. § 34.35.050 et seq.",
  },
  arizona: {
    name: "Arizona",
    slug: "arizona",
    abbreviation: "AZ",
    preliminaryNotice: {
      required: true,
      deadline: "20 days from first furnishing labor or materials (Preliminary 20-Day Notice)",
      whoToSendTo: "Property owner, general contractor, and construction lender",
    },
    lienDeadline: "120 days from completion of the project for subcontractors; 120 days for general contractors",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail or personal delivery within 5 days of recording",
    enforcementDeadline: "6 months from recording the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Ariz. Rev. Stat. § 33-981 et seq.",
  },
  arkansas: {
    name: "Arkansas",
    slug: "arkansas",
    abbreviation: "AR",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "120 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Circuit Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail",
    enforcementDeadline: "15 months from filing the lien",
    lienAmountLimits: "Limited to the value of labor or materials furnished",
    statute: "Ark. Code Ann. § 18-44-101 et seq.",
  },
  california: {
    name: "California",
    slug: "california",
    abbreviation: "CA",
    preliminaryNotice: {
      required: true,
      deadline: "20 days from first furnishing labor or materials (Preliminary Notice)",
      whoToSendTo: "Property owner, general contractor, and construction lender",
    },
    lienDeadline: "90 days from completion of the work of improvement for direct contractors; 90 days for all others (from completion or cessation of work)",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail, registered mail, or personal delivery within 10 days of recording",
    enforcementDeadline: "90 days from recording the lien",
    lienAmountLimits: "Limited to the reasonable value of labor, services, equipment, or materials furnished",
    statute: "Cal. Civ. Code § 8400 et seq.",
  },
  colorado: {
    name: "Colorado",
    slug: "colorado",
    abbreviation: "CO",
    preliminaryNotice: {
      required: true,
      deadline: "10 business days before filing lien (Notice of Intent to File Lien)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "4 months from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk and Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve Notice of Intent to File Lien on property owner by certified mail at least 10 business days before filing",
    enforcementDeadline: "6 months from filing the lien statement",
    lienAmountLimits: "Limited to the value of labor or materials furnished",
    statute: "Colo. Rev. Stat. § 38-22-101 et seq.",
  },
  connecticut: {
    name: "Connecticut",
    slug: "connecticut",
    abbreviation: "CT",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "90 days from last furnishing services or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Town Clerk's Office in the town where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail or personal service",
    enforcementDeadline: "1 year from filing the lien",
    lienAmountLimits: "Limited to the contract amount or reasonable value of services/materials",
    statute: "Conn. Gen. Stat. § 49-33 et seq.",
  },
  delaware: {
    name: "Delaware",
    slug: "delaware",
    abbreviation: "DE",
    preliminaryNotice: {
      required: true,
      deadline: "30 days from first furnishing labor or materials (Notice of Intent to Claim a Lien) for subcontractors",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "30 days from completion, acceptance, or last date of work",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Prothonotary's Office (Superior Court) in the county where the property is located",
    serviceRequirements: "Serve copy on property owner",
    enforcementDeadline: "1 year from filing the lien",
    lienAmountLimits: "Limited to the contract price",
    statute: "Del. Code Ann. tit. 25 § 2701 et seq.",
  },
  "district-of-columbia": {
    name: "District of Columbia",
    slug: "district-of-columbia",
    abbreviation: "DC",
    preliminaryNotice: {
      required: true,
      deadline: "Notice of Intent required within 90 days of completion of work",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last furnishing labor or materials (for subcontractors); 3 months from completion for general contractors",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Recorder of Deeds",
    serviceRequirements: "Serve Notice of Intent on property owner by certified mail",
    enforcementDeadline: "180 days from filing the lien",
    lienAmountLimits: "Limited to the value of labor or materials furnished",
    statute: "D.C. Code § 40-301.01 et seq.",
  },
  florida: {
    name: "Florida",
    slug: "florida",
    abbreviation: "FL",
    preliminaryNotice: {
      required: true,
      deadline: "45 days from first furnishing labor, services, or materials (Notice to Owner) for subcontractors and suppliers",
      whoToSendTo: "Property owner, general contractor, and surety (if applicable)",
    },
    lienDeadline: "90 days from last furnishing labor, services, or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "Clerk of Circuit Court in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 15 days of recording",
    enforcementDeadline: "1 year from recording the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials; for subs, limited to what is owed to them",
    statute: "Fla. Stat. § 713.01 et seq.",
  },
  georgia: {
    name: "Georgia",
    slug: "georgia",
    abbreviation: "GA",
    preliminaryNotice: {
      required: true,
      deadline: "Within 30 days of beginning work or delivering materials (Notice of Commencement filing by owner creates notice obligation for subs)",
      whoToSendTo: "Property owner and general contractor (for subcontractors and suppliers)",
    },
    lienDeadline: "90 days from completion of the work or from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Clerk of Superior Court in the county where the property is located",
    serviceRequirements: "Serve copy on property owner within 2 days of filing (by mail or personal delivery)",
    enforcementDeadline: "365 days from filing the lien",
    lienAmountLimits: "Limited to the value of labor or materials furnished",
    statute: "Ga. Code Ann. § 44-14-361 et seq.",
  },
  hawaii: {
    name: "Hawaii",
    slug: "hawaii",
    abbreviation: "HI",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "45 days from completion of the improvement; for subcontractors, within 45 days of completion of the entire project",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Bureau of Conveyances or Land Court",
    serviceRequirements: "Serve copy on property owner",
    enforcementDeadline: "3 months from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Haw. Rev. Stat. § 507-41 et seq.",
  },
  idaho: {
    name: "Idaho",
    slug: "idaho",
    abbreviation: "ID",
    preliminaryNotice: {
      required: true,
      deadline: "5 days before filing the lien (Notice of Claim of Lien must be sent to owner)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by personal delivery or certified mail at least 5 days before filing",
    enforcementDeadline: "6 months from filing the lien",
    lienAmountLimits: "Limited to the reasonable value of labor or materials furnished",
    statute: "Idaho Code § 45-501 et seq.",
  },
  illinois: {
    name: "Illinois",
    slug: "illinois",
    abbreviation: "IL",
    preliminaryNotice: {
      required: true,
      deadline: "Within 60 days of first furnishing labor or materials (subcontractors must notify owner)",
      whoToSendTo: "Property owner (for subcontractors and suppliers)",
    },
    lienDeadline: "4 months from completion of work for contractors; 4 months from last furnishing for subcontractors",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner and lender within 30 days of recording",
    enforcementDeadline: "2 years from completion of work",
    lienAmountLimits: "Subcontractors limited to the amount owed by owner to general contractor at time of notice",
    statute: "770 ILCS 60/1 et seq.",
  },
  indiana: {
    name: "Indiana",
    slug: "indiana",
    abbreviation: "IN",
    preliminaryNotice: {
      required: true,
      deadline: "Written copy of subcontract or purchase order required within 30 days of receiving payment (for certain claimants)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last furnishing labor, materials, or services",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 30 days of recording",
    enforcementDeadline: "1 year from recording the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Ind. Code § 32-28-3-1 et seq.",
  },
  iowa: {
    name: "Iowa",
    slug: "iowa",
    abbreviation: "IA",
    preliminaryNotice: {
      required: true,
      deadline: "Within 30 days of first furnishing labor or materials for subcontractors (Preliminary Notice)",
      whoToSendTo: "General contractor and property owner",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 10 days of filing",
    enforcementDeadline: "2 years from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value",
    statute: "Iowa Code § 572.1 et seq.",
  },
  kansas: {
    name: "Kansas",
    slug: "kansas",
    abbreviation: "KS",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "5 months from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Clerk of the District Court in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail or personal delivery",
    enforcementDeadline: "1 year from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Kan. Stat. Ann. § 60-1101 et seq.",
  },
  kentucky: {
    name: "Kentucky",
    slug: "kentucky",
    abbreviation: "KY",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required (but notice of nonpayment recommended)",
      whoToSendTo: "N/A",
    },
    lienDeadline: "6 months from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner within 30 days of filing",
    enforcementDeadline: "1 year from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Ky. Rev. Stat. § 376.010 et seq.",
  },
  louisiana: {
    name: "Louisiana",
    slug: "louisiana",
    abbreviation: "LA",
    preliminaryNotice: {
      required: true,
      deadline: "Notice of Contract must be filed before work begins (for general contractors); Notice of Nonpayment within 75 days of substantial completion (for subs)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "60 days from filing of Notice of Termination by owner, or within 60 days of substantial completion if no Notice of Termination is filed",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Clerk of Court / Mortgage Office in the parish where the property is located",
    serviceRequirements: "File Statement of Claim or Privilege; serve on property owner",
    enforcementDeadline: "1 year from filing the lien",
    lienAmountLimits: "Limited to the amount owed under the contract",
    statute: "La. Rev. Stat. § 9:4801 et seq.",
  },
  maine: {
    name: "Maine",
    slug: "maine",
    abbreviation: "ME",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Registry of Deeds in the county where the property is located",
    serviceRequirements: "Serve copy on property owner within the lien filing period",
    enforcementDeadline: "120 days from filing the lien",
    lienAmountLimits: "Limited to the contract price or fair value of labor/materials",
    statute: "Me. Rev. Stat. Ann. tit. 10 § 3251 et seq.",
  },
  maryland: {
    name: "Maryland",
    slug: "maryland",
    abbreviation: "MD",
    preliminaryNotice: {
      required: true,
      deadline: "Within 120 days of doing work or furnishing materials, subcontractors must give written notice",
      whoToSendTo: "Property owner and general contractor",
    },
    lienDeadline: "180 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Clerk of the Circuit Court in the county or Baltimore City where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail or personal delivery",
    enforcementDeadline: "1 year from filing the lien",
    lienAmountLimits: "Subcontractors limited to the amount owed by the owner to the general contractor",
    statute: "Md. Code Ann., Real Prop. § 9-101 et seq.",
  },
  massachusetts: {
    name: "Massachusetts",
    slug: "massachusetts",
    abbreviation: "MA",
    preliminaryNotice: {
      required: true,
      deadline: "Notice of Identification (sub-subcontractors must file within 30 days of starting work on residential projects)",
      whoToSendTo: "Property owner (for residential projects)",
    },
    lienDeadline: "120 days from last furnishing labor or materials (30 days for filing Statement of Account after Notice of Substantial Completion)",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Registry of Deeds in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 30 days of filing",
    enforcementDeadline: "30 days from filing (must file petition to enforce in court)",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Mass. Gen. Laws ch. 254 § 1 et seq.",
  },
  michigan: {
    name: "Michigan",
    slug: "michigan",
    abbreviation: "MI",
    preliminaryNotice: {
      required: true,
      deadline: "20 days from first furnishing labor or materials (Notice of Furnishing) for subcontractors",
      whoToSendTo: "Property owner, general contractor, and designee (if applicable)",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Register of Deeds in the county where the property is located",
    serviceRequirements: "Serve copy on property owner and general contractor by certified mail within 15 days of recording",
    enforcementDeadline: "1 year from last furnishing labor or materials",
    lienAmountLimits: "Limited to the amount of the contract or subcontract",
    statute: "Mich. Comp. Laws § 570.1101 et seq.",
  },
  minnesota: {
    name: "Minnesota",
    slug: "minnesota",
    abbreviation: "MN",
    preliminaryNotice: {
      required: true,
      deadline: "Within 45 days of first furnishing labor or materials (pre-lien notice) for persons not in privity with the owner",
      whoToSendTo: "Property owner and general contractor",
    },
    lienDeadline: "120 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Recorder or Registrar of Titles in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 10 days of filing",
    enforcementDeadline: "1 year from filing the lien statement",
    lienAmountLimits: "Limited to the value of labor, skill, material furnished",
    statute: "Minn. Stat. § 514.01 et seq.",
  },
  mississippi: {
    name: "Mississippi",
    slug: "mississippi",
    abbreviation: "MS",
    preliminaryNotice: {
      required: true,
      deadline: "30 days from first furnishing labor or materials for subcontractors (Notice to Owner)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last furnishing labor or materials for subcontractors; 90 days for general contractors from project completion",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Chancery Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail",
    enforcementDeadline: "180 days from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Miss. Code Ann. § 85-7-401 et seq.",
  },
  missouri: {
    name: "Missouri",
    slug: "missouri",
    abbreviation: "MO",
    preliminaryNotice: {
      required: true,
      deadline: "Within 5 days of filing the lien, must serve Notice of Lien on property owner",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "6 months from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Circuit Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve notice on property owner within 5 days of filing by certified mail or personal delivery",
    enforcementDeadline: "6 months from filing the lien",
    lienAmountLimits: "Limited to the contract price; subcontractors limited to amount owed by owner to contractor",
    statute: "Mo. Rev. Stat. § 429.010 et seq.",
  },
  montana: {
    name: "Montana",
    slug: "montana",
    abbreviation: "MT",
    preliminaryNotice: {
      required: true,
      deadline: "20 days from first furnishing labor or materials (Preliminary Notice) for subcontractors and suppliers",
      whoToSendTo: "Property owner, general contractor, and construction lender",
    },
    lienDeadline: "90 days from completion of the work of improvement",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk and Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 5 days of recording",
    enforcementDeadline: "2 years from filing the lien",
    lienAmountLimits: "Limited to the reasonable value of labor or materials furnished",
    statute: "Mont. Code Ann. § 71-3-521 et seq.",
  },
  nebraska: {
    name: "Nebraska",
    slug: "nebraska",
    abbreviation: "NE",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "120 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk's Office (Register of Deeds) in the county where the property is located",
    serviceRequirements: "Serve copy on property owner within 10 days of filing",
    enforcementDeadline: "2 years from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Neb. Rev. Stat. § 52-101 et seq.",
  },
  nevada: {
    name: "Nevada",
    slug: "nevada",
    abbreviation: "NV",
    preliminaryNotice: {
      required: true,
      deadline: "Within 31 days of first furnishing labor or materials (Notice of Right to Lien)",
      whoToSendTo: "Property owner, general contractor, and construction lender",
    },
    lienDeadline: "90 days after completion of the work of improvement or 40 days after owner records Notice of Completion",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 10 days of recording",
    enforcementDeadline: "6 months from recording the lien",
    lienAmountLimits: "Limited to the reasonable value of labor, materials, or equipment furnished",
    statute: "Nev. Rev. Stat. § 108.221 et seq.",
  },
  "new-hampshire": {
    name: "New Hampshire",
    slug: "new-hampshire",
    abbreviation: "NH",
    preliminaryNotice: {
      required: true,
      deadline: "Notice of Intent to File Lien must be sent at least 15 days before filing (for subcontractors on owner-occupied single-family residences)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "120 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Town or City Clerk's Office where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail",
    enforcementDeadline: "120 days from lien attachment date",
    lienAmountLimits: "Limited to the contract price or reasonable value",
    statute: "N.H. Rev. Stat. Ann. § 447:1 et seq.",
  },
  "new-jersey": {
    name: "New Jersey",
    slug: "new-jersey",
    abbreviation: "NJ",
    preliminaryNotice: {
      required: true,
      deadline: "Subcontractors must serve Notice of Unpaid Balance within 60 days of last furnishing; must serve within 90 days of completion of work on residential projects",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve Notice of Unpaid Balance on property owner",
    enforcementDeadline: "1 year from the date the debt became due and payable",
    lienAmountLimits: "Subcontractors limited to the amount owed to the general contractor by the owner",
    statute: "N.J. Stat. Ann. § 2A:44A-1 et seq.",
  },
  "new-mexico": {
    name: "New Mexico",
    slug: "new-mexico",
    abbreviation: "NM",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "120 days from completion of the project for residential; 120 days from last furnishing for commercial",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 15 days of filing",
    enforcementDeadline: "2 years from the date the lien was filed",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "N.M. Stat. Ann. § 48-2-1 et seq.",
  },
  "new-york": {
    name: "New York",
    slug: "new-york",
    abbreviation: "NY",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "8 months from last furnishing labor or materials (private projects); 30 days after completion and acceptance (public projects)",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner within 30 days of filing by personal service or certified mail",
    enforcementDeadline: "1 year from filing the lien (can be extended for 1 additional year)",
    lienAmountLimits: "Limited to the amount earned and unpaid; subcontractors limited to the amount owed by owner to contractor",
    statute: "N.Y. Lien Law § 1 et seq.",
  },
  "north-carolina": {
    name: "North Carolina",
    slug: "north-carolina",
    abbreviation: "NC",
    preliminaryNotice: {
      required: true,
      deadline: "Subcontractors must serve Notice to Lien Agent within 15 days of first furnishing labor or materials",
      whoToSendTo: "Lien agent designated by the property owner",
    },
    lienDeadline: "120 days from last furnishing labor or materials at the site",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Clerk of Superior Court in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within filing period",
    enforcementDeadline: "180 days from last furnishing labor or materials",
    lienAmountLimits: "Limited to the amount earned and unpaid on the project",
    statute: "N.C. Gen. Stat. § 44A-7 et seq.",
  },
  "north-dakota": {
    name: "North Dakota",
    slug: "north-dakota",
    abbreviation: "ND",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail or personal delivery within 5 days of filing",
    enforcementDeadline: "3 years from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "N.D. Cent. Code § 35-27-01 et seq.",
  },
  ohio: {
    name: "Ohio",
    slug: "ohio",
    abbreviation: "OH",
    preliminaryNotice: {
      required: true,
      deadline: "21 days from first furnishing labor or materials (Notice of Furnishing) for subcontractors and suppliers",
      whoToSendTo: "Property owner and general contractor",
    },
    lienDeadline: "75 days from last furnishing labor or materials (residential); 60 days for commercial",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner and general contractor by certified mail within 30 days of recording",
    enforcementDeadline: "6 years from filing the affidavit",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Ohio Rev. Code § 1311.01 et seq.",
  },
  oklahoma: {
    name: "Oklahoma",
    slug: "oklahoma",
    abbreviation: "OK",
    preliminaryNotice: {
      required: true,
      deadline: "Within 75 days of last furnishing labor or materials, subcontractors must file a Pre-Lien Notice",
      whoToSendTo: "Property owner and general contractor",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Pre-lien notice served on property owner and general contractor by certified mail",
    enforcementDeadline: "1 year from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Okla. Stat. tit. 42 § 141 et seq.",
  },
  oregon: {
    name: "Oregon",
    slug: "oregon",
    abbreviation: "OR",
    preliminaryNotice: {
      required: true,
      deadline: "8 days before filing the lien (Notice of Right to Lien must be sent to owner within 8 days of first furnishing for residential projects)",
      whoToSendTo: "Property owner and mortgage holder",
    },
    lienDeadline: "75 days from completion of construction; or 75 days from last furnishing labor/materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Clerk's / County Recorder's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 20 days of filing",
    enforcementDeadline: "120 days from filing the lien",
    lienAmountLimits: "Limited to the reasonable value of labor, materials, or equipment furnished",
    statute: "Or. Rev. Stat. § 87.001 et seq.",
  },
  pennsylvania: {
    name: "Pennsylvania",
    slug: "pennsylvania",
    abbreviation: "PA",
    preliminaryNotice: {
      required: true,
      deadline: "Subcontractors must serve Preliminary Notice within 30 days of first work on residential projects (under $500,000)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "6 months from completion of work (must first file a Praecipe to File Claim of Lien)",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Prothonotary's Office in the county where the property is located",
    serviceRequirements: "Serve Formal Notice on property owner by certified mail; for residential properties, must serve preliminary notice 30 days before filing",
    enforcementDeadline: "2 years from filing the lien",
    lienAmountLimits: "Limited to the contract price; subcontractors limited to the amount owed from the owner to contractor",
    statute: "49 Pa. Stat. § 1101 et seq.",
  },
  "rhode-island": {
    name: "Rhode Island",
    slug: "rhode-island",
    abbreviation: "RI",
    preliminaryNotice: {
      required: true,
      deadline: "Notice of Intention must be recorded and served at least 10 days before filing lien",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "200 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "City or Town Clerk where the property is located",
    serviceRequirements: "Serve Notice of Intention by certified mail at least 10 days before filing",
    enforcementDeadline: "40 days from filing the account",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "R.I. Gen. Laws § 34-28-1 et seq.",
  },
  "south-carolina": {
    name: "South Carolina",
    slug: "south-carolina",
    abbreviation: "SC",
    preliminaryNotice: {
      required: true,
      deadline: "Notice of Project Commencement must be filed by the owner; subcontractors must serve Notice of Furnishing within 90 days of last furnishing",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Clerk of Court or Register of Deeds in the county where the property is located",
    serviceRequirements: "Serve Notice of Filing on property owner within 15 days of filing by certified mail",
    enforcementDeadline: "6 months from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "S.C. Code Ann. § 29-5-10 et seq.",
  },
  "south-dakota": {
    name: "South Dakota",
    slug: "south-dakota",
    abbreviation: "SD",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "120 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Register of Deeds in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 5 days of filing",
    enforcementDeadline: "6 months from filing the lien",
    lienAmountLimits: "Limited to the value of labor or materials furnished",
    statute: "S.D. Codified Laws § 44-9-1 et seq.",
  },
  tennessee: {
    name: "Tennessee",
    slug: "tennessee",
    abbreviation: "TN",
    preliminaryNotice: {
      required: true,
      deadline: "Notice of Nonpayment must be served within 90 days of last furnishing labor or materials (for remote contractors/suppliers)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Register of Deeds in the county where the property is located",
    serviceRequirements: "Serve Notice of Nonpayment on property owner by registered or certified mail within 90 days of last furnishing",
    enforcementDeadline: "1 year from filing the lien, or 90 days from completion of project (whichever is later)",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Tenn. Code Ann. § 66-11-101 et seq.",
  },
  texas: {
    name: "Texas",
    slug: "texas",
    abbreviation: "TX",
    preliminaryNotice: {
      required: true,
      deadline: "Subcontractors must send notice by the 15th day of the 2nd month after labor/materials first furnished; original contractors must send notice by the 15th day of the 3rd month",
      whoToSendTo: "Property owner (for subcontractors and suppliers); no preliminary notice required for original contractors",
    },
    lienDeadline: "15th day of the 4th month after last furnishing labor or materials (for original contractors); 15th day of the 3rd month for subcontractors",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 5 days of filing",
    enforcementDeadline: "1 year from last day claimant could have filed the lien (2 years for residential)",
    lienAmountLimits: "Original contractors limited to contract price; subcontractors limited to the unpaid balance owed from owner to contractor",
    statute: "Tex. Prop. Code § 53.001 et seq.",
  },
  utah: {
    name: "Utah",
    slug: "utah",
    abbreviation: "UT",
    preliminaryNotice: {
      required: true,
      deadline: "20 days from first furnishing labor or materials (Preliminary Notice) for subcontractors and suppliers",
      whoToSendTo: "Property owner, general contractor, and State Construction Registry",
    },
    lienDeadline: "180 days from last furnishing labor or materials, or from completion of the original contract (whichever is earlier)",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Recorder's Office in the county where the property is located; must also file on State Construction Registry",
    serviceRequirements: "File Preliminary Notice on State Construction Registry; serve copy on property owner by certified mail within 30 days of recording",
    enforcementDeadline: "180 days from filing the lien",
    lienAmountLimits: "Limited to the reasonable value of labor, equipment, or materials furnished",
    statute: "Utah Code § 38-1a-101 et seq.",
  },
  vermont: {
    name: "Vermont",
    slug: "vermont",
    abbreviation: "VT",
    preliminaryNotice: {
      required: false,
      deadline: "No preliminary notice required",
      whoToSendTo: "N/A",
    },
    lienDeadline: "180 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier"],
    whereToFile: "Town Clerk's Office in the town where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail",
    enforcementDeadline: "180 days from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Vt. Stat. Ann. tit. 9 § 1921 et seq.",
  },
  virginia: {
    name: "Virginia",
    slug: "virginia",
    abbreviation: "VA",
    preliminaryNotice: {
      required: true,
      deadline: "Within 30 days of first furnishing labor or materials on residential projects (Preliminary Notice to Owner, for subcontractors/suppliers)",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "90 days from last day of the month in which the last labor/material was furnished, or 90 days from completion",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Circuit Court Clerk's Office in the county or city where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 30 days of recording for residential projects",
    enforcementDeadline: "6 months from recording the lien, or 60 days from completion (whichever is later)",
    lienAmountLimits: "Subcontractors limited to the amount owed by owner to the general contractor",
    statute: "Va. Code § 43-1 et seq.",
  },
  washington: {
    name: "Washington",
    slug: "washington",
    abbreviation: "WA",
    preliminaryNotice: {
      required: true,
      deadline: "60 days from first furnishing labor, materials, or equipment (Notice to Owner) for subcontractors",
      whoToSendTo: "Property owner and general contractor",
    },
    lienDeadline: "90 days from last furnishing labor, materials, or equipment",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer", "Equipment Rental"],
    whereToFile: "County Auditor's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail within 14 days of recording",
    enforcementDeadline: "8 months from filing the lien claim",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials/equipment",
    statute: "Wash. Rev. Code § 60.04.011 et seq.",
  },
  "west-virginia": {
    name: "West Virginia",
    slug: "west-virginia",
    abbreviation: "WV",
    preliminaryNotice: {
      required: true,
      deadline: "Within 60 days of first furnishing labor or materials, subcontractors must provide Notice of Right to Lien",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "100 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve Notice of Right to Lien on property owner by certified mail or personal delivery",
    enforcementDeadline: "6 months from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "W. Va. Code § 38-2-1 et seq.",
  },
  wisconsin: {
    name: "Wisconsin",
    slug: "wisconsin",
    abbreviation: "WI",
    preliminaryNotice: {
      required: true,
      deadline: "Within 60 days of first furnishing labor or materials for subcontractors and suppliers (Notice of Intent to File Lien must be served 30 days before filing)",
      whoToSendTo: "Property owner and general contractor",
    },
    lienDeadline: "6 months from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "Clerk of Circuit Court in the county where the property is located",
    serviceRequirements: "Serve Notice of Intent to File Lien on property owner and general contractor at least 30 days before filing",
    enforcementDeadline: "2 years from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Wis. Stat. § 779.01 et seq.",
  },
  wyoming: {
    name: "Wyoming",
    slug: "wyoming",
    abbreviation: "WY",
    preliminaryNotice: {
      required: true,
      deadline: "Preliminary notice must be given within 20 days of first furnishing labor or materials",
      whoToSendTo: "Property owner",
    },
    lienDeadline: "150 days from last furnishing labor or materials",
    whoCanFile: ["General Contractor", "Subcontractor", "Material Supplier", "Laborer"],
    whereToFile: "County Clerk's Office in the county where the property is located",
    serviceRequirements: "Serve copy on property owner by certified mail or personal delivery",
    enforcementDeadline: "180 days from filing the lien",
    lienAmountLimits: "Limited to the contract price or reasonable value of labor/materials",
    statute: "Wyo. Stat. § 29-2-101 et seq.",
  },
};
