import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Legal Disclaimer | LienFile.io",
  description:
    "Important legal disclaimer about AI-generated documents and the limitations of LienFile.io services.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-full bg-white">
      <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8">
        <h1 className="text-3xl font-bold text-[#1a2744] sm:text-4xl">
          Legal Disclaimer
        </h1>
        <p className="mt-4 text-sm text-slate-500">
          Last updated: January 1, 2025
        </p>

        <div className="mt-8 rounded-lg border border-amber-200 bg-amber-50 p-6">
          <div className="flex items-start gap-3">
            <svg
              className="mt-0.5 h-6 w-6 shrink-0 text-amber-600"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z"
              />
            </svg>
            <div>
              <h2 className="font-semibold text-amber-800">
                Important: Please Read Carefully
              </h2>
              <p className="mt-2 text-sm text-amber-700">
                LienFile.io is a document preparation service, not a law firm.
                The documents generated by our platform are created using
                artificial intelligence and automated systems. You should review
                all documents carefully before use.
              </p>
            </div>
          </div>
        </div>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-slate-600">
          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              Not Legal Advice
            </h2>
            <p className="mt-3">
              Nothing on this website or in any documents generated by
              LienFile.io constitutes legal advice. The information provided is
              for general informational purposes only. We are not attorneys and
              do not provide legal representation. The use of our service does
              not create an attorney-client relationship.
            </p>
            <p className="mt-3">
              If you need legal advice regarding your specific situation, we
              strongly recommend consulting with a licensed attorney in your
              state who specializes in construction law or mechanic&apos;s liens.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              AI-Generated Documents
            </h2>
            <p className="mt-3">
              Our platform uses artificial intelligence and automated systems to
              generate lien documents, preliminary notices, and related forms.
              While we strive for accuracy and regularly update our systems to
              reflect current state laws, AI-generated documents may contain
              errors or omissions. You are responsible for reviewing all
              documents for accuracy before filing or serving them.
            </p>
            <p className="mt-3">
              Specifically, you should verify:
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                All names, addresses, and property descriptions are correct
              </li>
              <li>
                Dollar amounts accurately reflect the sums owed to you
              </li>
              <li>
                Dates of work and other timeline information are accurate
              </li>
              <li>
                The document complies with your state&apos;s current statutory
                requirements
              </li>
              <li>
                The document is being filed within the applicable deadline
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              No Guarantee of Outcome
            </h2>
            <p className="mt-3">
              Filing a mechanic&apos;s lien does not guarantee that you will be
              paid. The effectiveness of a lien depends on many factors,
              including the accuracy of the information provided, compliance with
              state-specific requirements, timely filing and service, and the
              financial circumstances of the property owner. We make no
              representations or warranties about the legal sufficiency or
              effectiveness of any documents generated through our service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              State Law Variations
            </h2>
            <p className="mt-3">
              Mechanic&apos;s lien laws vary significantly from state to state.
              Requirements for form, content, deadlines, service, and
              enforcement differ across jurisdictions. While our system is
              designed to account for state-specific requirements, laws change
              frequently and there may be local requirements or recent statutory
              changes not yet reflected in our system.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              Filing Deadlines
            </h2>
            <p className="mt-3">
              Filing deadlines for mechanic&apos;s liens are strictly enforced.
              Missing a deadline can result in the permanent loss of your lien
              rights. While we provide deadline estimates based on the
              information you provide, these estimates are for informational
              purposes only. You are solely responsible for determining and
              meeting your actual filing deadline. We recommend consulting with
              an attorney if you are unsure about your deadline.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              Improper Lien Filing
            </h2>
            <p className="mt-3">
              Filing a mechanic&apos;s lien without a valid legal basis may
              expose you to liability for damages, including the property
              owner&apos;s attorney fees in some states. You should only file a
              lien if you have a legitimate, good-faith claim to payment for
              labor or materials provided to the property. We do not verify the
              validity of your underlying claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              Limitation of Liability
            </h2>
            <p className="mt-3">
              LienFile.io shall not be liable for any damages resulting from your
              use of documents generated through our service, including but not
              limited to damages resulting from errors or omissions in generated
              documents, missed deadlines, rejection of filings by government
              offices, or failure to recover payment. Our liability is limited to
              the amount you paid for our services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#1a2744]">
              Contact Us
            </h2>
            <p className="mt-3">
              If you have questions about this disclaimer or our services,
              contact us at:
            </p>
            <p className="mt-3">
              Email: legal@lienfile.io
              <br />
              LienFile.io
              <br />
              Attn: Legal
            </p>
          </section>
        </div>

        <div className="mt-12 border-t pt-8">
          <Link
            href="/"
            className="text-sm font-medium text-[#f97316] hover:text-[#ea580c]"
          >
            &larr; Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
